// This file is part of MARTY.
//
// MARTY is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// MARTY is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with MARTY. If not, see <https://www.gnu.org/licenses/>.

/**
 * @file libmakefile_data.h
 * @brief
 * @author Grégoire Uhlrich
 * @version 2.0
 * @date 2020-11-05
 */
#pragma once

#include <iostream>

void print_libmakefile_data(std::ostream      &out,
                            bool               quad,
                            std::string const &cppCompiler,
                            std::string const &cCompiler,
                            bool               optimize)

{
    out << "# Part common to all libraries generated by CSL\n";
    out << "\n";
    out << "CXX     = " << cppCompiler << "\n";
    out << "CC      = " << cCompiler << "\n";
    out << "CXXSTD  = -std=c++17\n";
    out << "CSTD    = -std=c11\n";
    out << "DEFAULTFLAGS = -Wall -Wextra -Wpedantic "
           "-Wno-deprecated-declarations -fPIC\n";

    if (optimize) {
        out << "MATH_OPTI = -Ofast\n\n";
        out << "OPTIFLAGS = -O2 $(MATH_OPTI)\n";
    }
    else {
        out << "OPTIFLAGS = \n";
    }
    if (!quad) {
        out << "CXXFLAGS  = $(CXXSTD) $(DEFAULTFLAGS) $(OPTIFLAGS)\n";
        out << "CFLAGS    = $(CSTD) $(DEFAULTFLAGS) $(OPTIFLAGS)\n";
        out << "LINKFLAGS = $(DEFAULTFLAGS)\n";
    }
    else {
        out << "QUADFLAGS = -DQUAD=1 -DQUADSIZE=16\n";
        out << "CXXFLAGS  = $(CXXSTD) $(DEFAULTFLAGS) $(OPTIFLAGS) "
               "$(QUADFLAGS)\n";
        out << "CFLAGS    = $(CSTD) $(DEFAULTFLAGS) $(OPTIFLAGS) "
               "$(QUADFLAGS)\n";
        out << "LINKFLAGS = $(DEFAULTFLAGS) $(QUADFLAGS)\n";
    }
    out << "\n";
    out << "SRCDIR = src\n";
    out << "INCDIR = include\n";
    out << "OBJDIR = obj\n";
    out << "CLIBDIR = clib\n";
    out << "SCRIPTDIR = script\n";
    out << "SOBJDIR = script/obj\n";
    out << "BINDIR = bin\n";
    out << "LIBDIR = lib\n";
    out << "\n";
    out << "SRC 	 = $(wildcard $(SRCDIR)/*.cpp)\n";
    out << "CSRC 	 = $(wildcard $(CLIBDIR)/*.c)\n";
    out << "HEADERS  = $(wildcard $(INCDIR)/*.h)\n";
    out << "OBJ      = $(SRC:$(SRCDIR)/%.cpp=$(OBJDIR)/%.o)\n";
    out << "COBJ     = $(CSRC:$(CLIBDIR)/%.c=$(CLIBDIR)/%.o)\n";
    out << "SCRIPTS  = $(wildcard $(SCRIPTDIR)/*.cpp)\n";
    out << "BINARIES = $(SCRIPTS:$(SCRIPTDIR)/%.cpp=%.x)\n";
    out << "SOBJ = $(SCRIPTS:$(SCRIPTDIR)/%.cpp=$(SOBJDIR)/%.o)\n";
    out << "\n";
    out << "all: scripts lib\n";
    out << "\n";
    out << "scripts: $(BINARIES)\n";
    out << "lib: $(NAMELIB).so $(NAMELIB).a\n";
    out << "\n";
    out << "$(CLIBDIR)/%.o: $(CLIBDIR)/%.c\n";
    out << "	$(CC) $(CFLAGS) -c $< -o $@ $(INCPATH)\n";
    out << "\n";
    out << "$(OBJDIR)/%.o: $(SRCDIR)/%.cpp\n";
    out << "	$(CXX) $(CXXFLAGS) -c $< -o $@ $(INCPATH)\n";
    out << "\n";
    out << "$(SOBJDIR)/%.o: $(SCRIPTDIR)/%.cpp\n";
    out << "	$(CXX) $(CXXFLAGS) -c $< -o $@ $(INCPATH)\n";
    out << "\n";
    out << "%.x: $(SOBJDIR)/%.o $(OBJ) $(COBJ)\n";
    out << "	$(CXX) $(CXXSTD) $(LINKFLAGS) -o $(BINDIR)/$@ $^ $(INCPATH) "
           "$(LIBPATH) $(LIBS)\n";
    out << "\n";
    out << "$(NAMELIB).so: $(OBJ) $(COBJ)\n";
    out << "	$(CXX) $(CXXFLAGS) -shared -o $(LIBDIR)/$@ $^ $(LIBPATH) "
           "$(LIBS)\n";
    out << "$(NAMELIB).a: $(OBJ) $(COBJ)\n";
    out << "	ar rcs $(LIBDIR)/$@ $^\n";
    out << "\n";
    out << "clean:\n";
    out << "	-rm $(OBJDIR)/*.o\n";
    out << "	-rm $(BINDIR)/*.x\n";
    out << "	-rm $(CLIBDIR)/*.o\n";
    out << "	-rm $(LIBDIR)/*.a\n";
    out << "	-rm $(LIBDIR)/*.so\n";
}
