#if 0
This file was generated by mkexternalsh on Fri 28 Aug 2020 08:25:47 AM CEST.
Do not edit.
#endif

#if NOUNDERSCORE

#define cachecopy ljcachecopy
#define cacheindex ljcacheindex

#else

#define cachecopy_ ljcachecopy_
#define cacheindex_ ljcacheindex_

#endif
