from typing import Union, Optional, List
import enum

class FierzBasis(enum.IntEnum):
    Standard = ...
    Chiral = ...

class Expr:
    def __init__(self, expr: Union[Expr, int, float]) -> None: ...
    def __neg__(self) -> Expr: ...
    def __add__(self, o: Expr) -> Expr: ...
    def __radd__(self, o: Expr) -> Expr: ...
    def __mul__(self, o: Expr) -> Expr: ...
    def __rmul__(self, o: Expr) -> Expr: ...
    def __sub__(self, o: Expr) -> Expr: ...
    def __rsub__(self, o: Expr) -> Expr: ...
    def __truediv__(self, o: Expr) -> Expr: ...
    def __rtruediv__(self, o: Expr) -> Expr: ...

# Options
def set_symbolic_dimension(keep_symbolic: bool) -> None: ...

# Tensors
def g(mu: int, nu: int) -> Expr: ...
def eps(mu: int, nu: int, rho: int, sigma: int) -> Expr: ...
def gamma(mu: int, nu: Optional[int] = None) -> Expr: ...
def gamma5() -> Expr: ...
def P_L() -> Expr: ...
def P_R() -> Expr: ...
def C() -> Expr: ...

# Fermion current definition
def current(gammas: List[Expr], left_index: int, right_index: int) -> Expr: ...

# Simplifications
def trace(gammas: List[Expr]) -> Expr: ...
def simplify(expr: Expr) -> Expr: ...
def order(expr: Expr) -> Expr: ...
def project(expr: Expr, basis: FierzBasis) -> Expr: ...
def single_fierz(
    left_current: Expr, right_current: Expr, basis: FierzBasis = FierzBasis.Chiral
) -> Expr: ...
def double_fierz(
    left_current: Expr, right_current: Expr, basis: FierzBasis = FierzBasis.Chiral
) -> Expr: ...

__all__ = [
    "Expr",
    "set_symbolic_dimension",
    "g",
    "eps",
    "gamma",
    "gamma5",
    "P_L",
    "P_R",
    "C",
    "current",
    "simplify",
    "order",
    "project",
    "single_fierz",
    "double_fierz",
    "trace",
    "FierzBasis",
]
