#if 0
This file was generated by mkexternalsh on Thu Apr 19 16:58:25 CEST 2018.
Do not edit.
#endif

#if NOUNDERSCORE

#define cachecopy ljcachecopy
#define cacheindex ljcacheindex

#else

#define cachecopy_ ljcachecopy_
#define cacheindex_ ljcacheindex_

#endif
